# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Configure Git
      run: git config --global core.symlinks false
      
    - uses: actions/checkout@v3  # Checkout the repository

    - name: Rename Long Paths in Backend
      run: |
        Get-ChildItem -Path ./backend -Recurse | ForEach-Object {
          if ($_.FullName.length -gt 255) {
            $newName = $_.Name.substring(0, 200) + $_.Name.substring($_.Name.length - 50)
            Rename-Item -Path $_.FullName -NewName $newName
          }
        }
      working-directory: ./backend

    - name: Rename Long Paths in Frontend
      run: |
        Get-ChildItem -Path ./frontend -Recurse | ForEach-Object {
          if ($_.FullName.length -gt 255) {
            $newName = $_.Name.substring(0, 200) + $_.Name.substring($_.Name.length - 50)
            Rename-Item -Path $_.FullName -NewName $newName
          }
        }
      working-directory: ./frontend

    - name: Install Backend Dependencies
      run: npm ci
      working-directory: ./backend

    - name: Install Frontend Dependencies
      run: npm ci
      working-directory: ./frontend

    - name: Build Frontend
      run: npm run build
      working-directory: frontend
